### ISSUE TITLE
ให้หัวข้อแสดงเต็มๆ ต้องแก้ตรงไหนครับ

### ISSUE THREAD

**Issue by melonpress** [JindaTheme/JindaAds#10]
พอดีผมเพิ่งมีโอกาสใช้ธีมนี้น่ะครับ แต่พบว่าหัวข้อบทความในหน้าแรกนั้นแสดงไม่ทั้งหมด(สั้น) แล้วมี ... ตาม ถ้าต้องการให้แสดงเต็มไม่ทราบว่าต้องแก้ไชตรงไหนเหรอครับ

ช่วยนี้แนะด้วยนะครับ
ขอบคุณครับ

**Comment by jir4yu** [comment]
ที่ Theme Options ให้เพิ่ม CSS ด้านล่างนี้ไปในส่วนของ Custom CSS ครับ

```
.list-item .post-title{
    overflow: initial;
    max-width: 100%;
    text-overflow: initial;
    white-space: initial;
}
```

**Comment by melonpress** [comment]
ขอบคุณครับ ได้แล้ว
