### ISSUE TITLE
YouTube ในหน้าบทความไม่ Responsive ครับ

### ISSUE THREAD

**Issue by huayai** [JindaTheme/JindaAds#11]
พอดีผมเห็นในเว็บตัวอย่างคลิป YouTube มัน responsive น่ะครับ

แต่พอทดสอบแล้ว ไม่ respon เลยครับ พอจะชี้แแนะให้หน่อยได้มั้ยครับ

**Comment by jir4yu** [comment]
ปรกติแล้ว copy embed code จาก youtube มาวางแล้วจะเป็น responsive layout ได้เลยนะครับ
ขอดูหน้าบทความที่บอกว่าไม่ responsive หน่อยครับ
