### ISSUE TITLE
thumbnail ในหน้า list เราสามารถ fix หรือ corp ภาพให้มันเล็กลงแล้วขนาด กว้างสูงเท่ากันได้ไหมครับ

### ISSUE THREAD

**Issue by sorawitkub** [JindaTheme/JindaAds#9]
thumbnail ในหน้า list (เฉพาะภาพตัวอย่าง) เราสามารถ  corp ภาพให้มันเล็กลงแล้วขนาด กว้างสูงเท่ากันได้ไหมครับ
เพื่อนๆหลายๆคนอาจจะมีปัญหาตรงนี้ในการอัพรูปกันนะครับต้องมาย่อส่วนให้เท่ากันจึงจะเป็นระเบียบมันอาจจะต้องเสียเวลาในการย่อภาพอีก

ผมเลยอยากทราบว่าเราพอมีวิธีเขียนโค้ดในการ corp ภาพยังไงให้มันช่วยประหยัดเวลาเราได้บางครับ
ขอคำแนะนำหน่อยได้ไหมครับ

ขอบคุณครับ

**Comment by jir4yu** [comment]
ในจุดที่เรียก thumbnail คือบรรทัดที่ 21 
(https://github.com/JindaTheme/JindaAds/blob/master/view-list.php#L21) 

ตรงนี้เรียก thumbnail ในขนาดที่สร้างขึ้นมาเองตะหาก ชื่อ jindacover ซึ่งสามารถเข้าไปค้นไฟล์ functions.php
แล้วเขียน size ของรูปที่ต้องการเพิ่มเข้าไปแทนได้ครับ ดูตัวอย่างได้จาก https://developer.wordpress.org/reference/functions/add_image_size/

**Comment by sorawitkub** [comment]
ขอบคุณมากครับสำหรับคำแนะนำ ตอนนี้ได้แล้วครับขนาดภาพเท่ากันทุกอันไม่ต้องมานั้งย่อเองอีกแล้ว

สวยขึ้นเลยครับภาพเท่ากัน
http://www.mx7.com/i/89d/R0M9F4.png

**Comment by sorawitkub** [comment]
ขออนุญาติตรงนี้เลยแล้วกัน นำเอาไปโมต่อยอดอีกนิดพอดีเป็นคนชอบสไตล์นี้เป็นธีมพื้นฐานโมง่ายมากเลยครับ
ขอบคุณสำหรับคำแนะนำอีกครั้ง

คอม
http://www.mx7.com/i/966/7lLE07.png

ในมือถือ
http://www.mx7.com/i/bb9/R5n4yV.png
